spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888/"
#    import: "optional:configserver:http://config-server:8888/"