server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/josematosvicente/bootcamp-cloud-config.git
          default-label: dev
          search-paths: config-data
          username: josematosvicente
          password: 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
